//Model
const menuButtonAndSearchBar = /*HTML*/`
    <h1>Turtle Movies</h1>
    <div class="dropdown">
    <button class="dropbtn">Menu</button>
    <div class="dropdown-content">
        <button onclick="mainPageView()">Main Page</button>
        <button onclick="profilePageView()">Profile Page</button>
        <br>
        <button onclick="userLogout()">Logout</button>
        <!-- Add more buttons here if needed -->
    </div>
    </div>

    <!--Search for title function -->
    <div class="searchDiv">
    <input type="text" id="searchInput" placeholder="Search for Movie Titles...">
    <button class="searchButton" onclick="performSearch()">Search</button>
    </div>
`;

const model = {
    app: {
        loggedInUser: [],
        currentPage: 'loginPage',
        cinemaMode: true,
        pages: [
            'loginPage',
            'homePage',
            'profilePage',
            'moviePage',
            'searchPage',
        ],
    },
    inputs: {
        rateNewMovie: null,
        user: {
            id: null, 
            displayName: '',
            userName: '',
            password: '',
            emailAdress: '',
            favGenre: [],
            favMovies: [],
            myRatedMovies: [],
            aboutMe: '',
            profileImage: '',
        },
        search: '',
        //nice to have filter: [],
    },
    //Data
    data: {
        search: '',
        //nice to have filter: [''],
        users:[
            {
                id: 1,
                displayName: 'Martini',
                userName: 'Martin',
                password: 'shaken',
                emailAdress: 'martini@getacademy.no',
                favGenre: ['Adventure','Fantasy',],
                favMovies: ['The Dukes of Hazzard','The Grudge (2004)',],
                myRatedMovies: ['The Dukes of Hazzard','The Grudge (2004)',],
                aboutMe: 'Jeg liker Martini!',     
                profileImage: './img/profileImages/emptyUser.jpg',

            },
            {
                id: 2, 
                displayName: '',
                userName: '',
                password: '',
                emailAdress: 'dummmyBruker@hotmail.com',
                favGenre: ['Action', 'Fantasy'],
                favMovies: [],
                myRatedMovies: [],
                aboutMe: 'Im a dummy user',
                profileImage: './img/profileImages/emptyUser.jpg',
            },
            {
                id: 3, 
                displayName: 'Ellie',
                userName: 'Ellie',
                password: '1234',
                emailAdress: 'elliemarie@getacademy.no',
                favGenre: ['Fantasy', 'Adventure', 'Horror'],
                favMovies: [],
                myRatedMovies: [],
                aboutMe: 'Part of the development team! ',
                profileImage: './img/profileImages/emptyUser.jpg',
            },
            {
                id: 4, 
                displayName: 'Espen',
                userName: 'Espen',
                password: '1234',
                emailAdress: 'espenh@getacademy.no',
                favGenre: [],
                favMovies: [],
                myRatedMovies: [],
                aboutMe: 'Part of the development team!',
                profileImage: './img/profileImages/emptyUser.jpg',
            },
            {
                id: 5, 
                displayName: 'Ellen',
                userName: 'Ellen',
                password: '1234',
                emailAdress: 'ellenbirgittea@getacademy.no',
                favGenre: ['Fantasy', 'Crime', 'Adventure'],
                favMovies: [],
                myRatedMovies: [],
                aboutMe: 'Part of the development team!',
                profileImage: './img/profileImages/emptyUser.jpg',
            },
            {
                id: 6, 
                displayName: 'Markus',
                userName: 'Markus',
                password: '1234',
                emailAdress: 'markus@getacademy.no',
                favGenre: [],
                favMovies: [],
                myRatedMovies: [],
                aboutMe: 'Part of the development team!',
                profileImage: './img/profileImages/emptyUser.jpg',
            },
            {
                id: 7, 
                displayName: 'Tor',
                userName: 'Tor',
                password: '1234',
                emailAdress: 'toralver@getacademy.no',
                favGenre: [],
                favMovies: [],
                myRatedMovies: [],
                aboutMe: 'Part of the development team!',
                profileImage: './img/profileImages/emptyUser.jpg',
            },
        ], 
        genre: [],

        highestRated: [],       
        movies: [
            // {
            //     id: 1,
            //     title: '',
            //     releaseDate: '',
            //     cover: '',
            //     duration: '',
            //     description: "",
            //     overallRating: '',
            //     personalRating: '',
            //     genre: [''],
            //     directors: [''],
            //     staringActors: [''],
            // },
            {
                id: 2,
                title: 'The Dukes of hazzard',
                releaseDate: '2005',
                cover: './img/coverImages/dukesOfHazzard.jpg',
                duration: '1h and 44m',
                description: "Cousins Bo, Luke, and Daisy Duke, and their uncle Jesse, egg on the authorities of Hazzard County, Boss Hogg and Sheriff Coltrane",
                overallRating: '510',
                personalRating: null,
                genre: ['Comedy'],
                directors: ['Jay Chandrasekhar'],
                staringActors: ['Seann William Scott', 'Johnny Knoxville', 'Jessica Simpson'],
            },
            {
                id: 3,
                title: 'The Grudge (2004)',
                releaseDate: '2004',
                cover: './img/coverImages/theGrudge.jpg',
                duration: '1h and 31m',
                description: "An American nurse living and working in Tokyo is exposed to a mysterious supernatural curse, one that locks a person in a powerful rage before claiming their life and spreading to another victim.",
                overallRating: '590',
                personalRating: null,
                genre: ['Horror', 'Mystery', 'Thriller'],
                directors: ['Takashi Shimizu'],
                staringActors: ['Sarah Michelle Gellar', 'Jason Behr', 'Clea DuVall'],
            },
            {
                id: 4,
                title: 'Titanic',
                releaseDate: '1997',
                cover: './img/coverImages/titanic.jpg',
                duration: '3h and 14m',
                description: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
                overallRating: '790',
                personalRating: null,
                genre: ['Drama', 'Romance'],
                directors: ['James Cameron'],
                staringActors: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane'],
            },
            {
                id: 5,
                title: 'Jurassic Park',
                releaseDate: '1993',
                cover: './img/coverImages/jurassicPark.jpg',
                duration: '2h and 7m',
                description: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
                overallRating: '820',
                personalRating: null,
                genre: ['Action', 'Adventure', 'Sci-Fi'],
                directors: ['Steven SpielBerg'],
                staringActors: ['Sam Niell', 'Laura Dern', 'Jeff Goldblum'],
            },
            {
                id: 6,
                title: 'Forrest Gump',
                releaseDate: '1994',
                cover: './img/coverImages/forrestGump.jpg',
                duration: '2h and 22m',
                description: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
                overallRating: '882',
                personalRating: null,
                genre: ['Drama', 'Romance'],
                directors: ['Robert Zemeckis'],
                staringActors: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
            },
            {
                id: 7,
                title: 'The Godfather',
                releaseDate: '1972',
                cover: './img/coverImages/thegodfather.jpg',
                duration: '2h and 55m',
                description: "Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.",
                overallRating: '920',
                personalRating: null,
                genre: ['Crime', 'Drama'],
                directors: ['Francis Ford Coppola'],
                staringActors: ['Marlon Brando', 'Al Pacino', 'James Caan'],
            },
            {
                id: 8,
                title: 'The Dark Knight',
                releaseDate: '2008',
                cover: './img/coverImages/thedarkknight.jpg',
                duration: '2h and 32 min',
                description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                overallRating: '900',
                personalRating: null,
                genre: ['Action', 'Crime', 'Drama', 'Thriller'],
                directors: ['Christopher Nolan'],
                staringActors: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
            },
            {
                id: 9,
                title: 'The Lord of the Rings: The Fellowship of the Ring',
                releaseDate: '2001',
                cover: './img/coverImages/lotrfellowship.jpg',
                duration: '2h and 58m',
                description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
                overallRating: '880',
                personalRating: null,
                genre: ['Action', 'Adventure', 'Drama', 'Fantasy'],
                directors: ['Peter Jackson'],
                staringActors: ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom'],
            },
            {
                id: 10,
                title: 'Interstellar',
                releaseDate: '2014',
                cover: './img/coverImages/interstellar.jpg',
                duration: '2h and 49m',
                description: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
                overallRating: '870',
                personalRating: null,
                genre: ['Adventure', 'Drama', 'Sci-Fi'],
                directors: ['Christopher Nolan'],
                staringActors: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
            },
            {
                id: 11,
                title: "Schindler's List",
                releaseDate: '1993',
                cover: './img/coverImages/schindlerslist.jpg',
                duration: '3h and 15m',
                description: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
                overallRating: '900',
                personalRating: null,
                genre: ['Biography', 'Drama', 'History'],
                directors: ['Steven Spielberg'],
                staringActors: ['Liam Neeson', 'Ralph Fiennes', 'Ben Kingsley'],
            },
            {
                id: 12,
                title: 'Pulp Fiction',
                releaseDate: '1994',
                cover: './img/coverImages/pulpfiction.jpg',
                duration: '2h and 34m',
                description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                overallRating: '890',
                personalRating: null,
                genre: ['Crime', 'Drama'],
                directors: ['Quentin Tarantino'],
                staringActors: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
            },
            {
                id: 13,
                title: 'Fight Club',
                releaseDate: '1999',
                cover: './img/coverImages/fightclub.jpg',
                duration: '2h and 19m',
                description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
                overallRating: '880',
                personalRating: null,
                genre: ['Drama'],
                directors: ['David Fincher'],
                staringActors: ['Brad Pitt', 'Edward Norton', 'Meat Loaf'],
            },
            {
                id: 14,
                title: 'Gladiator',
                releaseDate: '2000',
                cover: './img/coverImages/gladiator.jpg',
                duration: '2h and 35m',
                description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
                overallRating: '850',
                personalRating: null,
                genre: ['Action', 'Adventure', 'Drama'],
                directors: ['Ridley Scott'],
                staringActors: ['Russell Crowe', 'Joaquin Phoenix','Connie Nielsen'],
            },
            {
                id: 15,
                title: 'Inglourious Basterds',
                releaseDate: '2009',
                cover: './img/coverImages/inglouriousbasterds.jpg',
                duration: '2009',
                description: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.",
                overallRating: '840',
                personalRating: null,
                genre: ['Adventure', 'Drama', 'War'],
                directors: ['Quentin Tarantino'],
                staringActors: ['Brad Pitt','Diane Kruger', 'Eli Roth'],
            },
            {
                id: 16,
                title: 'Kimi no na wa. (Your Name.)',
                releaseDate: '2016',
                cover: './img/coverImages/yourname.jpg',
                duration: '1h and 46m',
                description: "Two teenagers share a profound, magical connection upon discovering they are swapping bodies. Things manage to become even more complicated when the boy and girl decide to meet in person.",
                overallRating: '840',
                personalRating: null,
                genre: ['Animation', 'Drama', 'Fantasy', 'Romance'],
                directors: ['Makoto Shinkai'],
                staringActors: ['Ryunosuke Kamiki', 'Mone Kamishiraishi', 'Ryo Narita'],
            },
            {
                id: 17,
                title: "Five Night's at Freddy's",
                releaseDate: '2003',
                cover: './img/coverImages/freddys.jpg',
                duration: '1h and 50m',
                description: "A troubled security guard begins working at Freddy Fazbear's Pizza. During his first night on the job, he realizes that the night shift won't be so easy to get through. Pretty soon he will unveil what actually happened at Freddy's.",
                overallRating: '820',
                personalRating: null,
                genre: ['Horror', 'Mystery', 'Thriller'],
                directors: ['Emma Tammi'],
                staringActors: ['Josh Hutcherson', 'Mary Stuart Masterson', 'Lucas Grant'],
            },
            {
                id: 18,
                title: 'Oppenheimer',
                releaseDate: '2003',
                cover: './img/coverImages/oppenheimer.jpg',
                duration: '3h',
                description: "The story of American scientist, J. Robert Oppenheimer, and his role in the development of the atomic bomb.",
                overallRating: '850',
                personalRating: null,
                genre: ['Biography', 'Drama', 'History'],
                directors: ['Christopher Nolan'],
                staringActors: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon'],
            },
            {
                id: 19,
                title: 'The Lord of the Rings: The Two Towers',
                releaseDate: '2002',
                cover: './img/coverImages/lotrtwotowers.jpg',
                duration: '2h and 59m',
                description: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
                overallRating: '880',
                personalRating: null,
                genre: ['Action', 'Adventure', 'Drama', 'Fantasy'],
                directors: ['Peter Jackson'],
                staringActors: ['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen'],
            },
            {
                id: 20,
                title: 'The Lord of the Rings: The Return of the King',
                releaseDate: '2003',
                cover: './img/coverImages/lotrreturnoftheking.jpg',
                duration: '3h and 21m',
                description: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                overallRating: '900',
                personalRating: null,
                genre: ['Action', 'Adventure', 'Drama', 'Fantasy'],
                directors: ['Peter Jackson'],
                staringActors: ['Elijah Wood', 'Viggo Mortensen', 'Ian McKellen'],
            },
            {
                id: 21,
                title: 'The Matrix',
                releaseDate: '1999',
                cover: './img/coverImages/thematrix.jpg',
                duration: '2h and 16m',
                description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
                overallRating: '870',
                personalRating: null,
                genre: ['Action', 'Sci-Fi'],
                directors: ['Lana Wachowski', 'Lilly Wachowski'],
                staringActors: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
            },
            {
                id: 22,
                title: 'Elvis',
                releaseDate: '2022',
                cover: './img/coverImages/elvis.jpg',
                duration: '2h and 39m',
                description: "The life of American music icon Elvis Presley, from his childhood to becoming a rock and movie star in the 1950s while maintaining a complex relationship with his manager, Colonel Tom Parker.",
                overallRating: '730',
                personalRating: null,
                genre: ['Biography', 'Drama', 'Music'],
                directors: ['Baz Luhrmann'],
                staringActors: ['Tom Hanks', 'Austin Butler', 'Olivia DeJonge'],
            },
            {
                id: 23,
                title: 'The Godfather Part II',
                releaseDate: '1974',
                cover: './img/coverImages/thegodfatherparttwo.jpg',
                duration: '3h and 22m',
                description: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
                overallRating: '900',
                personalRating: null,
                genre: ['Crime', 'Drama'],
                directors: ['Francis Ford Coppola'],
                staringActors: ['Al Pacino', 'Robert De Niro', 'Robert Duvall'],
            },
            {
                id: 24,
                title: 'The Godfather Part III',
                releaseDate: '1990',
                cover: './img/coverImages/thegodfatherpartthree.jpg',
                duration: '2h and 42m',
                description: "Follows Michael Corleone, now in his 60s, as he seeks to free his family from crime and find a suitable successor to his empire.",
                overallRating: '760',
                personalRating: null,
                genre: ['Crime', 'Drama'],
                directors: ['Francis Ford Coppola'],
                staringActors: ['Al Pacino', 'Diane Keaton', 'Andy Garcia'],
            },
            {
                id: 25,
                title: 'Bohemian Rhapsody',
                releaseDate: '2018',
                cover: './img/coverImages/bohemianrhapsody.jpg',
                duration: '2h and 14m',
                description: "The story of the legendary British rock band Queen and lead singer Freddie Mercury, leading up to their famous performance at Live Aid (1985).",
                overallRating: '790',
                personalRating: null,
                genre: ['Biography', 'Drama', 'Music'],
                directors: ['Bryan Singer'],
                staringActors: ['Rami Malek', 'Lucy Boynton', 'Gwilym Lee'],
            },
            {
                id: 26,
                title: 'The Pianist',
                releaseDate: '2002',
                cover: './img/coverImages/thepianist.jpg',
                duration: '2h and 30m',
                description: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
                overallRating: '850',
                personalRating: null,
                genre: ['Biography', 'Drama', 'Music', 'War'],
                directors: ['Roman Polanski'],
                staringActors: ['Adrien Brody', 'Thomas Kretschmann', 'Frank Finlay'],
            },
            {
                id: 27,
                title: 'Inception',
                releaseDate: '2010',
                cover: './img/coverImages/inception.jpg',
                duration: '2h and 28m',
                description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
                overallRating: '880',
                personalRating: null,
                genre: ['Action', 'Adventure', 'Sci-Fi', 'Thriller'],
                directors: ['Christopher Nolan'],
                staringActors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
            },
            {
                id: 28,
                title: 'Toy Story',
                releaseDate: '1995',
                cover: './img/coverImages/toystory.jpg',
                duration: '1h and 21m',
                description: "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy's bedroom.",
                overallRating: '830',
                personalRating: null,
                genre: ['Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy'],
                directors: ['John Lasseter'],
                staringActors: ['Tom Hanks', 'Tim Allen', 'Don Rickles'],
            },
            {
                id: 29,
                title: 'Strange Days',
                releaseDate: '1995',
                cover: './img/coverImages/strangedays.jpg',
                duration: '2h and 25m',
                description: "A former cop turned street-hustler accidentally uncovers a conspiracy in Los Angeles in 1999.",
                overallRating: '720',
                personalRating: null,
                genre: ['Crime', 'Drama', 'Sci-Fi', 'Thriller'],
                directors: ['Kathryn Bigelow'],
                staringActors: ['Ralph Fiennes', 'Angela Bassett', 'Juliette Lewis'],
            },
            {
                id: 30,
                title: 'Frozen',
                releaseDate: '2013',
                cover: './img/coverImages/frozen.jpg',
                duration: '1h and 42m',
                description: "When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.",
                overallRating: '740',
                personalRating: null,
                genre: ['Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Musical'],
                directors: ['Chris Buck', 'Jennifer Lee'],
                staringActors: ['Kristen Bell', 'Idina Menzel', 'Jonathan Groff'],
            },
            {
                id: 31,
                title: 'Frozen II',
                releaseDate: '2019',
                cover: './img/coverImages/frozentwo.jpg',
                duration: '1h and 43m',
                description: "Anna, Elsa, Kristoff, Olaf and Sven leave Arendelle to travel to an ancient, autumn-bound forest of an enchanted land. They set out to find the origin of Elsa's powers in order to save their kingdom.",
                overallRating: '680',
                personalRating: null,
                genre: ['Animation', 'Adventure', 'Comedy', 'Drama', 'Family', 'Fantasy', 'Musical'],
                directors: ['Chris Buck', 'Jennifer Lee'],
                staringActors: ['Kristen Bell', 'Idina Menzel',' Josh Gad'],
            },
            {
                id: 32,
                title: 'Akira',
                releaseDate: '1988',
                cover: './img/coverImages/akira.jpg',
                duration: '2h and 4m',
                description: "A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic psychopath who can only be stopped by a teenager, his gang of biker friends and a group of psychics.",
                overallRating: '800',
                personalRating: null,
                genre: ['Animation', 'Action', 'Drama', 'Fantasy', 'Sci-Fi', 'Thriller'],
                directors: ['Katsuhiro Ôtomo'],
                staringActors: ['Mitsuo Iwata', 'Nozomu Sasaki', 'Mami Koyama'],
            },
                                                                   
                  
        ],
    },
}